name: 'Algos Module 3 Task 1 Khizhnyakov Vadim'
on: [pull_request, push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Configure
      run: mkdir build && cd build && cmake .. && make
    - name: Work
      run: cd build && ./Graph